version: '3.0'
services:
    myredis:
        image: redis:3.2-alpine
        #restart: always
        container_name: redis_single
        ports:
            - "6379:6379"

networks:
    default:
        external:
            name: mynet
