version: '3.0'

services:
    fastdfs:
        build: .
        image: lee/fastdfs:5.10
        # restart: always
        container_name: fastdfs
        environment:
            - WEB_PORT=8888
            - IP=192.168.0.110
        volumes:
            - /home/docker/fdfs:/var/local/fdfs
        privileged: true
        network_mode: "host"
# 此处采用host方式网络，即容器共用主机的网络设置。
# 若采用bridge方式网络，容器内部设置为
#        ports:
#            - "80:8888"
#            - "22122:22122"
#            
#networks:
#    default:
#        external:
#            name: mynet

